steps:
  - label: ":python: Run Tests"    
    command:
      - "python3 -m venv venv"
      - "source venv/bin/activate"
      - "pip install -r requirements.txt"
      - "pip install -e .[test]"
      - "pytest tests/"
